# Generated by Django 4.0.5 on 2022-11-01 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_product_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
