# Generated by Django 4.0.5 on 2022-11-01 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_product_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
